{% set name = "verticapy" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/verticapy-{{ version }}.tar.gz
  sha256: beff959af5b31965c50dccee9e2a8ce83a5378a6a7d3463948e9ad17495fefd6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - matplotlib-base
    - numpy
    - python >=2.7
    - scipy
    - vertica-python
    - python-dateutil

test:
  imports:
    - verticapy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vertica/VerticaPy
  summary: VerticaPy simplifies data exploration, data cleaning and machine learning in Vertica.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FernandezMathieu
